export const addvText = [
  "🎁🎁luckky winner",
  "💥💥win upto 100000...",
  "🔊last chance win upto 1cr",
  "🎉🎉lucky winner",
  "🔥🔥Google pay lucky winner",
  "🎁🎁Get a chance to win exciting prizes!",
  "💥💥Win big with our latest contest!",
  "🔊Hurry! Limited time offer!",
  "🎉🎉You could be our next lucky winner!",
  "🔥🔥Amazing prizes up for grabs!",
  "🎁🎁Enter now for a chance to win!",
  "💥💥Join the contest and win big!",
  "🔊Don't miss out on this opportunity!",
  "🎉🎉Winning is just a click away!",
  "🔥🔥Get ready to be a winner!",
  "🎁🎁Enter our giveaway and win big!",
  "💥💥New contest alert!",
  "🔊Limited period offer, grab it now!",
  "🎉🎉The more you participate, the higher your chances of winning!",
  "🔥🔥Play now and stand a chance to win!",
  "🎁🎁Take part and win exciting rewards!",
  "💥💥Join now and get a chance to win!",
  "🔊Last chance to win big!",
  "🎉🎉Our contest has amazing prizes in store for you!",
  "🔥🔥Make your dreams come true with our contest!",
  "🎁🎁Winning has never been easier!",
  "💥💥Get a chance to win cash prizes!",
  "🔊Enter the contest and win exclusive rewards!",
  "🎉🎉Join now and win big!",
  "🔥🔥Amazing rewards waiting for you!",
  "🎁🎁Participate now and win exciting gifts!",
  "💥💥The contest with the biggest prizes!",
  "🔊Don't wait, start winning now!",
  "🎉🎉Get ready for an exciting adventure!",
  "🔥🔥Enter the contest and win like never before!",
  "🎁🎁Be a part of our winning team!",
  "💥💥Join now and get a chance to win big!",
  "🔊You could be the next lucky winner!",
  "🎉🎉Take part in our contest and win amazing prizes!",
  "🔥🔥Play now and win like never before!",
  "🎁🎁Get a chance to win exclusive rewards!",
  "💥💥Enter our contest and win exciting prizes!",
  "🔊Hurry up and join our winning team!",
  "🎉🎉Amazing prizes just a click away!",
  "🔥🔥Play now and get a chance to win big!",
  "🎁🎁Take part and win like never before!",
  "💥💥Join now and be a part of the winning team!",
  "🔊Don't miss out on the chance to win big!",
  "🎉🎉Amazing rewards up for grabs!",
];
